# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d15505d437166172e9236a1d83b62835d7c86488d42606bb9db415674778324617fb84e5978e8b5d727a61c928bf3ea56136a6007cda0e8433bb3dc2798bbeb0

test:
  secret_key_base: bc3879d049d4a1d2775e1b3fb478dac5eeaffb448e2114e1f3fb2398fecfd1ddee264b5a60922675eac90760b4a4173ac8c8a1bc940c0cfc3e7e1e560421bddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
